Add files via upload
csunibo/metodi-logici-per-la-filosofia pull request #14
Opened 2024-05-10 10:44 UTC by giorgiadalpra

2024-05-10 11:12 UTC, foxyseta requested changes
Ciao Giorgia! Ho dato l'esame con Orlandelli anno scorso (e ora sono alla magistrale di Logica che consiglia sempre lui). Bellissima questa presentazione, complimenti!

Come specificato [nella nostra documentazione](https://csunibo.github.io/wiki/raccolte-di-risorse/), di solito preferiamo i `.tex` ai `.pdf` (tanto la conversione in PDF viene fatta in automatico). In questo modo, se in futuro altre persone vogliono ispirarsi/imparare i comandi $\LaTeX$ che hai usato tu, possono consultarli liberamente.

Riusciresti a cancellare il `.pdf` e caricare invece il `.tex`, per favore? A parte l'estensione, il resto del nome del file va benissimo. Grazie!

2024-05-14 13:29 UTC, giorgiadalpra commented
Ciao! Grazie mille per i complimenti e ti chiedo scusa per il disturbo. Non ho mai usato GitHub quindi scusami per i casini, ora ho ricaricato il file in formato .tex come mi hai chiesto, stavo cercando di eliminare il documento pdf, ma non riesco.

2024-05-14 13:36 UTC, giorgiadalpra commented
Ok, ora in teoria sono riuscita ad eliminare il file .pdf e a caricare il .tex. Spero sia tutto a posto. Ti ringrazio ancora

2024-05-14 14:34 UTC, foxyseta commented
Grazie a te! Non mi ero accorto che il `.tex` richiama anche l'immagine `godel.png`. Caricheresti anche quella?

2024-05-14 16:42 UTC, foxyseta approved these changes

2024-05-14 16:42 UTC, merged

2024-05-14 16:50 UTC, foxyseta commented
Ottimo! D'ora in poi le diapositive sono consultabili qui: https://risorse.students.cs.unibo.it/metodi-logici-per-la-filosofia/prove Grazie ancora!